/**
 * Generated from src/v6/external-api/api.json and src/v6/source.json.
 * Do not edit this file directly. Run npm run generate:dts instead.
 */
export type TallyApi = {
    masters: {
        units: {
            /** Runs tally.masters.units.fetch and returns Tally's raw XML response. */
            fetch: (company: string) => Promise<string>;
        };
        stockItems: {
            /** Runs tally.masters.stockItems.withBatches and returns Tally's raw XML response. */
            withBatches: (company: string) => Promise<string>;
        };
        ledgers: {
            /** Runs tally.masters.ledgers.withGstDetails and returns Tally's raw XML response. */
            withGstDetails: (company: string) => Promise<string>;
        };
        stockGroup: {
            /** Runs tally.masters.stockGroup.withParent and returns Tally's raw XML response. */
            withParent: (company: string) => Promise<string>;
        };
    };
};

declare const tally: TallyApi;

export default tally;
