/**
 * Generated by create-intellisense from src/v7.
 * Do not edit this file directly.
 */

export type TallyApi = {
    masters: {
        units: {
            /** Runs tally.masters.units.fetch. */
            fetch: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
        stockItems: {
            /** Runs tally.masters.stockItems.withBatches. */
            withBatches: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
        ledgers: {
            /** Runs tally.masters.ledgers.withGstDetails. */
            withGstDetails: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
        stockGroup: {
            /** Runs tally.masters.stockGroup.withParent. */
            withParent: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
    };
};

declare const tally: TallyApi;

export default tally;
